{"name": "Создание заказа с авторизацией и с неправильными ингредиентами", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался статус 500, но получен 400. Текст: <!DOCTYPE html>\n  <html lang=\"en\">\n  <head>\n  <meta charset=\"utf-8\">\n  <title>Error</title>\n  </head>\n  <body>\n  <pre>Bad Request</pre>\n  </body>\n  </html>\n  \nassert 400 == 500\n +  where 400 = <Response [400]>.status_code", "trace": "self = <tests.test_create_order.TestApiCreateOrderPost object at 0x10e403f50>\nfixture_creating_order_with_authorization_invalid_ingredients = ('Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmE5N2E0OWVkMjgwMDAxYjViZmQyYyIsImlhdCI6MTc0NDQ3NjA2OSwiZXhw...zBqLC11noSRl0dLNbrCzLTW8Xfcw', \"'ingredients': ['61c0c5a71d', '61c0c5a71d1f82001bdaaa70', '61c0c5a71d1f82001bdaaa72']\")\n\n    @allure.title(\"Создание заказа с авторизацией и с неправильными ингредиентами\")\n    def test_creating_order_with_authorization_invalid_ingredients(self, fixture_creating_order_with_authorization_invalid_ingredients):\n        accessToken, order = fixture_creating_order_with_authorization_invalid_ingredients\n    \n        headers = {\n            \"Authorization\": f\"{accessToken}\",\n            \"Content-Type\": \"application/json\"\n        }\n    \n        with allure.step(\"Создаем заказ\"):\n            response = requests.post(api_orders_url, json=order, headers=headers)\n            allure.attach(f\"Response: {response.text}\")\n    \n        with allure.step(\"Проверяем код ответа\"):\n>           assert response.status_code == 500, f\"Ожидался статус 500, но получен {response.status_code}. Текст: {response.text}\"\nE           AssertionError: Ожидался статус 500, но получен 400. Текст: <!DOCTYPE html>\nE             <html lang=\"en\">\nE             <head>\nE             <meta charset=\"utf-8\">\nE             <title>Error</title>\nE             </head>\nE             <body>\nE             <pre>Bad Request</pre>\nE             </body>\nE             </html>\nE             \nE           assert 400 == 500\nE            +  where 400 = <Response [400]>.status_code\n\ntests/test_create_order.py:70: AssertionError"}, "steps": [{"name": "Создаем заказ", "status": "passed", "attachments": [{"source": "fe73c2c4-53bf-4c12-b66a-256dd84c8fa9-attachment.attach"}], "start": 1744476069138, "stop": 1744476069223}, {"name": "Проверяем код ответа", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался статус 500, но получен 400. Текст: <!DOCTYPE html>\n  <html lang=\"en\">\n  <head>\n  <meta charset=\"utf-8\">\n  <title>Error</title>\n  </head>\n  <body>\n  <pre>Bad Request</pre>\n  </body>\n  </html>\n  \nassert 400 == 500\n +  where 400 = <Response [400]>.status_code\n", "trace": "  File \"/Users/misolka/Downloads/Diplom/Diplom_2 /tests/test_create_order.py\", line 70, in test_creating_order_with_authorization_invalid_ingredients\n    assert response.status_code == 500, f\"Ожидался статус 500, но получен {response.status_code}. Текст: {response.text}\"\n"}, "start": 1744476069223, "stop": 1744476069223}], "start": 1744476069137, "stop": 1744476069224, "uuid": "024b53d1-a9b3-4b2e-8585-5d8a4e912640", "historyId": "96620944a5ec677d82bd2159e47c6585", "testCaseId": "96620944a5ec677d82bd2159e47c6585", "fullName": "tests.test_create_order.TestApiCreateOrderPost#test_creating_order_with_authorization_invalid_ingredients", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestApiCreateOrderPost"}, {"name": "host", "value": "MacBook-Air-Alina.local"}, {"name": "thread", "value": "12998-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}